export const MONEY_FIELDS = new Set([
  "averageSalary",
  "buildingLease",
  "electricity",
  "internet",
  "servers",
  "maintenance",
  "security",
  "genesysCost",
  "crmCost",
  "otherSoftware",
  "recruitment",
  "training",
  "otherExpenses",
  "projectCost",
  "monthlySavings",
  "licenseCost",
  "costPerFte",
]);

export const PERCENT_FIELDS = new Set([
  "occupancy",
  "shrinkage",
  "currentOccupancy",
  "targetOccupancy",
  "currentContainment",
  "targetContainment",
  "sla",
  "utilization",
  "abandonRate",
  "fcr",
  "csat",
]);

export const defaultAssumptions = {
  contactsPerAgent: 650,
  costPerFte: 52000,
  productiveHoursPerMonth: 168,
  ahtMinutes: 6,
};

export const calculators = [
  {
    id: "cost",
    title: "Contact Center Cost Calculator",
    category: "Cost Intelligence",
    description: "Model the complete monthly and annual run cost of a contact center.",
    accent: "from-electric to-violet",
    fields: [
      { id: "agents", label: "Agents", value: 120 },
      { id: "averageSalary", label: "Average Salary", value: 48000 },
      { id: "teamLeaders", label: "Team Leaders", value: 8 },
      { id: "assistantManagers", label: "Assistant Managers", value: 3 },
      { id: "operationsManagers", label: "Operations Managers", value: 2 },
      { id: "directors", label: "Directors", value: 1 },
      { id: "buildingLease", label: "Building Lease", value: 82000 },
      { id: "electricity", label: "Electricity", value: 18000 },
      { id: "internet", label: "Internet", value: 9500 },
      { id: "servers", label: "Servers", value: 21000 },
      { id: "maintenance", label: "Maintenance", value: 12500 },
      { id: "security", label: "Security", value: 11000 },
      { id: "genesysCost", label: "Genesys Cost", value: 64000 },
      { id: "crmCost", label: "CRM Cost", value: 35000 },
      { id: "otherSoftware", label: "Other Software", value: 14500 },
      { id: "recruitment", label: "Recruitment", value: 9000 },
      { id: "training", label: "Training", value: 15000 },
      { id: "otherExpenses", label: "Other Expenses", value: 12000 },
    ],
  },
  {
    id: "fte",
    title: "FTE Calculator",
    category: "Workforce Planning",
    description: "Estimate staffing demand from volume, handling time, occupancy, and shrinkage.",
    accent: "from-signal to-electric",
    fields: [
      { id: "calls", label: "Calls", value: 85000 },
      { id: "aht", label: "AHT", value: 6 },
      { id: "occupancy", label: "Occupancy", value: 82 },
      { id: "shrinkage", label: "Shrinkage", value: 28 },
      { id: "workingHours", label: "Working Hours", value: 168 },
      { id: "currentFte", label: "Current FTE", value: 125 },
    ],
  },
  {
    id: "roi",
    title: "ROI Calculator",
    category: "Investment Case",
    description: "Turn transformation cost and savings into a board-ready payback view.",
    accent: "from-emerald-400 to-signal",
    fields: [
      { id: "projectCost", label: "Project Cost", value: 420000 },
      { id: "monthlySavings", label: "Monthly Savings", value: 68000 },
    ],
  },
  {
    id: "aht",
    title: "AHT Savings Calculator",
    category: "Efficiency",
    description: "Quantify the benefit of reducing handle time across monthly interactions.",
    accent: "from-violet to-fuchsia-400",
    fields: [
      { id: "currentAht", label: "Current AHT", value: 7.2 },
      { id: "targetAht", label: "Target AHT", value: 6.1 },
      { id: "calls", label: "Calls", value: 85000 },
      { id: "costPerFte", label: "Cost Per FTE", value: 52000 },
    ],
  },
  {
    id: "occupancy",
    title: "Occupancy Calculator",
    category: "Capacity",
    description: "Show how occupancy improvement translates into capacity and FTE optimization.",
    accent: "from-amber-300 to-electric",
    fields: [
      { id: "currentOccupancy", label: "Current Occupancy", value: 74 },
      { id: "targetOccupancy", label: "Target Occupancy", value: 84 },
      { id: "currentFte", label: "Current FTE", value: 125 },
      { id: "costPerFte", label: "Cost Per FTE", value: 52000 },
    ],
  },
  {
    id: "ivr",
    title: "IVR Containment Calculator",
    category: "Automation",
    description: "Estimate avoided live-agent calls from stronger IVR containment.",
    accent: "from-sky-300 to-violet",
    fields: [
      { id: "calls", label: "Calls", value: 85000 },
      { id: "currentContainment", label: "Current Containment", value: 18 },
      { id: "targetContainment", label: "Target Containment", value: 34 },
      { id: "costPerFte", label: "Cost Per FTE", value: 52000 },
    ],
  },
  {
    id: "genesys",
    title: "Genesys License Optimization Calculator",
    category: "Licensing",
    description: "Identify unused seats, license utilization, and recurring waste.",
    accent: "from-electric to-cyan-300",
    fields: [
      { id: "namedLicenses", label: "Named Licenses", value: 180 },
      { id: "concurrentLicenses", label: "Concurrent Licenses", value: 95 },
      { id: "activeUsers", label: "Active Users", value: 142 },
      { id: "licenseCost", label: "License Cost", value: 125 },
    ],
  },
  {
    id: "health",
    title: "Contact Center Health Score",
    category: "Maturity",
    description: "Weighted operational maturity score across architecture, controls, and resilience.",
    accent: "from-lime-300 to-signal",
    fields: [
      { id: "architecture", label: "Architecture", value: 78 },
      { id: "security", label: "Security", value: 72 },
      { id: "routing", label: "Routing", value: 68 },
      { id: "reporting", label: "Reporting", value: 74 },
      { id: "automation", label: "Automation", value: 58 },
      { id: "licensing", label: "Licensing", value: 66 },
      { id: "governance", label: "Governance", value: 70 },
      { id: "disasterRecovery", label: "Disaster Recovery", value: 62 },
      { id: "analytics", label: "Analytics", value: 64 },
      { id: "businessContinuity", label: "Business Continuity", value: 69 },
    ],
  },
  {
    id: "kpi",
    title: "Contact Center KPI Dashboard",
    category: "Executive View",
    description: "Track SLA, AHT, occupancy, shrinkage, utilization, abandon rate, FCR, and CSAT.",
    accent: "from-fuchsia-400 to-electric",
    fields: [
      { id: "sla", label: "SLA", value: 82 },
      { id: "aht", label: "AHT", value: 6.4 },
      { id: "occupancy", label: "Occupancy", value: 79 },
      { id: "shrinkage", label: "Shrinkage", value: 27 },
      { id: "utilization", label: "Utilization", value: 76 },
      { id: "abandonRate", label: "Abandon Rate", value: 5.8 },
      { id: "fcr", label: "FCR", value: 71 },
      { id: "csat", label: "CSAT", value: 84 },
    ],
  },
  {
    id: "opportunity",
    title: "Optimization Opportunity Analyzer",
    category: "Prioritization",
    description: "Combine calculator outputs into prioritized NexCX service recommendations.",
    accent: "from-violet to-signal",
    fields: [],
  },
];
